variables:
  MAVEN_OPTS: -Dmaven.repo.local=.m2/repository

image: maven:latest

stages:
  - build
  - test
  - package
  - docker-image
  - docker-container

cache:
  paths:
    - .m2/repository
    - target

build_job:
  stage: build
  tags:
    - docker
  script:
    - echo "Maven compile started"
    - mvn compile

test_job:
  stage: test
  tags:
    - docker
  script:
    - echo "Maven test started"
    - mvn test

package_job:
  stage: package
  tags:
    - docker
  script:
    - echo "Maven packaging started"
    - mvn package

docker-image:
  image: docker:latest
  stage: docker-image
  tags:
    - docker
  services:
    - name: docker:dind
  script:
    - echo "Deploying application..."
    - docker build -t indumathi2906/gitlab-springboot-docker:latest . -f Dockerfile
    - echo "Login to docker hub..."
    - echo "$DOCKER_REGISTRY_PASSWORD" | docker login --username="$DOCKER_HUB_USERNAME" --password-stdin
    - echo "Pushing to docker..."
    - docker push indumathi2906/gitlab-springboot-docker:latest
    - echo "Application successfully deployed in Docker"
    - echo "You can check it in the Docker registry now"

docker-container:
  image: docker:latest
  stage: docker-container
  tags:
    - docker
  services:
    - name: docker:dind
  script:
    - echo "Running the Docker container..."
    - docker run -d -p 1123:8080 indumathi2906/gitlab-springboot-docker:latest
    - echo "Docker container is running."
